### ISSUE TITLE
Local Attention Model and Content-based Function

### ISSUE THREAD

**Issue by giancds** [harvardnlp/seq2seq-attn#18]
Hello guys,

Thanks for sharing this amazing repository with us! It will be very useful for a lot of people :-)

Quick questions:

1) Which of the content-based functions are you using: dot, general or concat?

2) Do you guys have any plans of implementing the local attention part of Luong's et al. (2015) paper?

Thanks again for sharing the code

**Comment by yoonkim** [comment]
Hi!
1) we use the 'general' attention model. we've found it to perform similarly to the concat model while being more memory efficient and faster.
2) we do not have plans to implement the local attention part
