### ISSUE TITLE
preprocess fails on sample data

### ISSUE THREAD

**Issue by gaphex** [harvardnlp/seq2seq-attn#19]
python preprocess.py --srcfile data/src-train.txt --targetfile data/targ-train.txt
fails with the following output:
Number of sentences in training: 10000
Traceback (most recent call last):
  File "preprocess.py", line 343, in <module>
    sys.exit(main(sys.argv[1:]))
  File "preprocess.py", line 340, in main
    get_data(args)
  File "preprocess.py", line 257, in get_data
    args.seqlength, max_word_l, args.chars)
  File "preprocess.py", line 79, in make_vocab
    enumerate(itertools.izip(open(srcfile,'r'), open(targetfile,'r'))):
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by yoonkim** [comment]
hi, it seems like you are not specificing the srcvalfile and targetvalfiles?

**Comment by srush** [comment]
Yoon, let's have this fail in a nicer way. You should be able to add `required=True` to those args.

**Comment by yoonkim** [comment]
yep, made those changes--closing now
