### ISSUE TITLE
Train from issue

### ISSUE THREAD

**Issue by penguinshin** [harvardnlp/seq2seq-attn#20]
Hi, sorry for not replying! I am still having the same issue where loading a model gives the empty tensor error. have you had this issue still?

**Comment by yoonkim** [comment]
if I recall correctly I think the previous train_from error was not an empty tensor error.
Can you post your command line as well as the error it gives?

**Comment by penguinshin** [comment]
Thanks for responding yoon! I just looked at the previous post I made and it was an empty tensor error. 

Here is the new one. Keep in mind that my run_model2.py encodes all the command line things. 

Would i be able to send you this file over email?



Austins-MacBook-Pro:src2anno austinshin$ python run_model2.py
loading data...	
done!	
Source vocab size: 8814, Target vocab size: 15669	
Source max sent len: 50, Target max sent len: 52	
loading django-model_final1.t7...	
Number of parameters: 14535669	
/Users/austinshin/torch/install/bin/luajit: bad argument #1 to '?' (empty tensor at /Users/austinshin/torch/pkg/torch/generic/Tensor.c:888)
stack traceback:
	[C]: at 0x0f9afad0
	[C]: in function '__index'
	/Users/austinshin/torch/install/share/lua/5.1/nn/MM.lua:51: in function 'updateGradInput'
	...stinshin/torch/install/share/lua/5.1/nngraph/gmodule.lua:386: in function 'neteval'
	...stinshin/torch/install/share/lua/5.1/nngraph/gmodule.lua:420: in function 'updateGradInput'
	...stinshin/torch/install/share/lua/5.1/nngraph/gmodule.lua:386: in function 'neteval'
	...stinshin/torch/install/share/lua/5.1/nngraph/gmodule.lua:420: in function 'updateGradInput'
	/Users/austinshin/torch/install/share/lua/5.1/nn/Module.lua:31: in function 'backward'
	train.lua:370: in function 'train_batch'
	train.lua:479: in function 'train'
	train.lua:646: in function 'main'
	train.lua:649: in main chunk
	[C]: in function 'dofile'
	...shin/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x010f647bc0

**Comment by yoonkim** [comment]
ah ok. yes, please send the file over email!

**Comment by penguinshin** [comment]
thanks!

**Comment by penguinshin** [comment]
let me know if you get the file. im not sure if it sent

**Comment by yoonkim** [comment]
hmm i didn't get it...

**Comment by penguinshin** [comment]
here it is as a text file, just change the extension to py
[run_model2.txt](https://github.com/harvardnlp/seq2seq-attn/files/244471/run_model2.txt)

**Comment by yoonkim** [comment]
hmm can you add the following two lines and print out the log here?

line 616: print(opt.num_layers, model_opt.num_layers)
line 369: print(#drnn_state_dec)

**Comment by penguinshin** [comment]
Austins-MacBook-Pro:src2anno austinshin$ python run_model2.py
loading data...	
done!	
Source vocab size: 8814, Target vocab size: 15669	
Source max sent len: 50, Target max sent len: 52	
loading django-model_final1.t7...	
2	2	
Number of parameters: 14535669	
5	
/Users/austinshin/torch/install/bin/luajit: bad argument #1 to '?' (empty tensor at /Users/austinshin/torch/pkg/torch/generic/Tensor.c:888)
stack traceback:

**Comment by yoonkim** [comment]
huh, weird. that looks right. 
let's debug this in person tomorrow? i should be in my office most of the afternoon

**Comment by penguinshin** [comment]
sounds good. wheres your office?

**Comment by yoonkim** [comment]
MD208

**Comment by penguinshin** [comment]
I printed out decoder_input (line 370) does this look right? 

Austins-MacBook-Pro:src2anno austinshin$ python run_model2.py
loading data...	
done!	
Source vocab size: 8814, Target vocab size: 15669	
Source max sent len: 50, Target max sent len: 52	
loading django-model_final1.t7...	
2	2	
Number of parameters: 14535669	
5	
{
  1 : LongTensor - size: 64
  2 : DoubleTensor - size: 64x12x100
  3 : DoubleTensor - size: 64x100
  4 : DoubleTensor - size: 64x100
  5 : DoubleTensor - size: 64x100
  6 : DoubleTensor - size: 64x100
  7 : DoubleTensor - size: 64x100
}
/Users/austinshin/torch/install/bin/luajit: bad argument #1 to '?' (empty tensor at /Users/austinshin/torch/pkg/torch/generic/Tensor.c:888)
stack traceback:






It’s odd because when I run a new training (when i don’t have the train_from) I get this (along with no error):


{
  1 : LongTensor - size: 64
  2 : DoubleTensor - size: 64x6x100
  3 : DoubleTensor - size: 64x100
  4 : DoubleTensor - size: 64x100
  5 : DoubleTensor - size: 64x100
  6 : DoubleTensor - size: 64x100
  7 : DoubleTensor - size: 64x100
}

**Comment by penguinshin** [comment]
So for some reason, when I do train_from, the value of source_l is 12 instead of 6 for normal training (without train_from). i think this might be the issue

**Comment by penguinshin** [comment]
Hi yoon I just stopped by your office- will
Be in md for the next hour or so let me know if your here!

**Comment by yoonkim** [comment]
hey sorry im in my office now!

**Comment by Sarah20187** [comment]
How do you fix this problem? I got a same one?
