### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by zhongzho** [harvardnlp/seq2seq-attn#24]
Hi all, 

I was running the test in pretrained model, I received the following error: 

 th beam.lua -model trained_models/en-to-de-model.t7 -src_file data/german/src-val.txt -output_file german_pred.txt -src_dict trained_models/en.dict -targ_dict trained_models/de.dict
loading trained_models/en-to-de-model.t7...
done!
SENT 1: Parliament Does Not Support Amendment Freeing Tymoshenko
/home/zzhong/torch/install/bin/luajit: beam.lua:163: attempt to perform arithmetic on field 'input_feed' (a nil value)
stack traceback:
        beam.lua:163: in function 'generate_beam'
        beam.lua:632: in function 'main'
        beam.lua:667: in main chunk
        [C]: in function 'dofile'
        ...hong/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x004064d0

Cheers,
Zhong

**Comment by yoonkim** [comment]
thanks for catching this--this is due to the pretrained models being trained without the options that were added later on (attn, brnn, input_feed).

i've pushed a fix for this. let me know if it works!
