### ISSUE TITLE
Invalid device ordinal

### ISSUE THREAD

**Issue by nicolas-ivanov** [harvardnlp/seq2seq-attn#27]
Thank you for a marvelous library!
I'm trying to train a demo model on a GPU, however I get the following error:

```
ubuntu@testing:~/nicolas/seq2seq-attn$ th train.lua -data_file data/demo-train.hdf5 -val_data_file data/demo-val.hdf5 -savefile demo-model -gpuid 0
using CUDA on GPU 0...	
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-1657/cutorch/init.c line=711 error=10 : invalid device ordinal
/home/ubuntu/torch/install/bin/luajit: train.lua:770: cuda runtime error (10) : invalid device ordinal at /tmp/luarocks_cutorch-scm-1-1657/cutorch/init.c:711
stack traceback:
	[C]: in function 'setDevice'
	train.lua:770: in function 'main'
	train.lua:874: in main chunk
	[C]: in function 'dofile'
	...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
```
Any suggestions on how it can be fixed?

All the Lua packages (hdf5, nngraph, cutorch, cunn) seem to be installed properly.

**Comment by yoonkim** [comment]
Hi, maybe try -gpuid 1?

**Comment by nicolas-ivanov** [comment]
Tried this already...

**Comment by yoonkim** [comment]
hmm seems like a driver issue:

https://devtalk.nvidia.com/default/topic/518479/invalid-device-ordinal-i-can-39-t-find-any-help-about-this-/?offset=3

**Comment by nicolas-ivanov** [comment]
Wow, thanks a lot! I'll check this up and report back to you.

**Comment by nicolas-ivanov** [comment]
@yoonkim your link helped, thank you!
Apparently, torch was trying to use the default version of cuda instead of the latest one.
So I had to append the following lines to my `~/.bashrc` file

```bash
export CUDA_HOME=/usr/local/cuda-7.5 
export LD_LIBRARY_PATH=${CUDA_HOME}/lib64 

PATH=${CUDA_HOME}/bin:${PATH} 
export PATH
```
and restart the bash session.
