### ISSUE TITLE
cuda runtime error on ubuntu 16.04 LTS / cuda 8.0

### ISSUE THREAD

**Issue by kitofans** [harvardnlp/seq2seq-attn#35]
I'm seeing
``` 
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-299/cutorch/lib/THC/THCGeneral.c line=608 error=4 : unspecified launch failure
/home/ankit/torch/install/bin/luajit: cuda runtime error (4) : unspecified launch failure at /tmp/luarocks_cutorch-scm-1-299/cutorch/lib/THC/generic/THCStorage.c:147
```
when running default training. i'm on ubuntu 16.04 with cuda 8.0 RC. it seems likely that there's a problem with cutorch and cuda 8.0 (the failure happens sometimes before a single batch is evaluated on, sometimes after -- the nondeterminism makes me think it's a fundamental driver problem), but before i either switch back to cuda 7.5 or ubuntu 14.04 or dive into the cutorch code, I was wondering if anything sticks out to you concerning this bug.

**Comment by yoonkim** [comment]
hmm i don't think i remember encountering that. i would recommend trying cuda 7.5 first (this is what we use).
