### ISSUE TITLE
Training Seq2Seq models for modelling conversations

### ISSUE THREAD

**Issue by vikram-gupta** [harvardnlp/seq2seq-attn#39]
Hello,

This is not an issue but a call for some guidance. Has anyone tried using this amazing project to train seq2seq models for generating conversations like [https://arxiv.org/pdf/1506.05869.pdf]

Thanks

**Comment by yoonkim** [comment]
i've experimented a little bit with dialogue and i observe similar results to those of non-attentional seq2seq models--responses tend to be quite generic ("i don't know." "yes." "no." etc,)

**Comment by vikram-gupta** [comment]
Thanks @yoonkim
