### ISSUE TITLE
Creation of vocabularies

### ISSUE THREAD

**Issue by ozancaglayan** [harvardnlp/seq2seq-attn#42]
Hi,

I observed that the `preprocess.py` script uses both training and validation corpora to generate the word dictionaries. Generally the source and target vocabularies are created only from training corpora. What's the intuition behind using both because you will never update the embeddings of the words only appearing in validation set?

**Comment by yoonkim** [comment]
good call--that is a mistake on our part.

**Comment by yoonkim** [comment]
fixed, thanks!
