### ISSUE TITLE
Create Character level data-set using shards 

### ISSUE THREAD

**Issue by mdasadul** [harvardnlp/seq2seq-attn#43]
I was trying to create character level dataset by adding 'chars' flag 1. My training data consists of  several source and target files because I am planning to use shards . When I am running preprocess.py I need to specify both train and validation data. The problem is I have several set of train files but one set of validation files. So I am not sure how to specify one set of validation file with each set of training file.  
I am doing something like this 
python preprocess.py --srcfile ../Train/src-train2.txt --targetfile ../Train/targ-train2.txt --srcvalfile ../Val/src-valid.txt --targetvalfile ../Val/targ-valid.txt --chars 1 --outputfile data/train2 

Also I realize that in each case it's creating new dictionary for vocabulary but I think it should use same vocabulary for all shard?  
Is there any other way to perform this task?

Thanks

**Comment by yoonkim** [comment]
Hi there!

- yes, you will need to use the same vocab. you can do this by creating the vocab on the first shard, and then using the created *.src.dict and *.targ.dict files as arguments into --srcvocabfile and --targetvocabfile in preprocess.py

- its ok to make the (same) validation file multiple times. you just need to pass in one validation file to -val_data_file.

- the naming convention for using shards can be found in train.lua

I actually suggest modifying preprocess.py to create shards from a big file (instead of running preprocess.py on a bunch of smaller files).

Hope this helps!

**Comment by mdasadul** [comment]
Thank you so much for clarification. I am not sure If I use the vocab on the first shard for all other the vocab will change or still it will be same as first shard?

**Comment by yoonkim** [comment]
it will be the same as the first shard

**Comment by mdasadul** [comment]
I think that's one of the problem. Anyway I will modify  preprocess.py to create shards from a big file. Thanks for your insight

**Comment by yoonkim** [comment]
here is the preprocessing file i used to use to create shards (arguments are slightly diff, but --shardsize specifies how many sentences it stores in each shard).

https://github.com/harvardnlp/seq2seq-attn/blob/master/preprocess-shards.py

**Comment by mdasadul** [comment]
I think there is a bug in your preprocess-shards.py. It's creating 126Mx2 shards file from 2M src/targ-train file.  Please see memory usages down below and I am using the demo data you provided in data dir

total 345M
-rwxrwxrwx 1 root root   1M Sep 26 12:03 demo.char.dict*
-rwxrwxrwx 1 root root   1M Sep 26 12:05 demo.src.dict*
-rwxrwxrwx 1 root root   1M Sep 26 12:05 demo.targ.dict*
-rwxrwxrwx 1 root root  12M Sep 26 12:05 demo-train.hdf5*
-rwxrwxrwx 1 root root 126M Sep 26 12:03 demo-train.hdf5.1.hdf5*
-rwxrwxrwx 1 root root 126M Sep 26 12:04 demo-train.hdf5.2.hdf5*
-rwxrwxrwx 1 root root   4M Sep 26 12:05 demo-val.hdf5*
-rwxrwxrwx 1 root root  71M Sep 26 12:03 demo-val.hdf5.1.hdf5*
-rwxrwxrwx 1 root root   1M Sep 26 11:31 src-test-case.txt*
-rwxrwxrwx 1 root root   1M Sep 26 11:31 src-test.txt*
-rwxrwxrwx 1 root root   3M Sep 26 11:31 src-train-case.txt*
-rwxrwxrwx 1 root root   2M Sep 26 11:31 src-train.txt*
-rwxrwxrwx 1 root root   1M Sep 26 11:31 src-val-case.txt*
-rwxrwxrwx 1 root root   1M Sep 26 11:31 src-val.txt*
-rwxrwxrwx 1 root root   1M Sep 26 11:31 targ-test.txt*
-rwxrwxrwx 1 root root   2M Sep 26 11:31 targ-train.txt*
-rwxrwxrwx 1 root root   1M Sep 26 11:31 targ-val.txt*

Thanks

**Comment by yoonkim** [comment]
Hi there. Are you using the character-level preprocesing? How does the size
compare with non-sharded data?

**Comment by mdasadul** [comment]
non-shards data is 12M and after using shards its 260M
