### ISSUE TITLE
Using this for sorting

### ISSUE THREAD

**Issue by ch3njust1n** [harvardnlp/seq2seq-attn#47]
Hi, I generated my own dataset with string sequences of random numbers and associated sorted string sequences or floats. I think I trained the network correctly - just followed the instructions on the page. Does it make sense to try to train this network to learn how to sort float values?

When I ran the command:
th evaluate.lua -model demo-model_final.t7 -src_file data/src-val.txt -output_file pred.txt
-src_dict data/demo.src.dict -targ_dict data/demo.targ.dict

Nothing was written to predict.txt, so I'm guessing I did something wrong or this network cannot learn to sort.

**Comment by yoonkim** [comment]
You probably need a larger dataset
