### ISSUE TITLE
Character vectors

### ISSUE THREAD

**Issue by alashkari** [harvardnlp/seq2seq-attn#50]
Hello,
I was wondering what model or method is used in this code in order to obtain the character vectors? 
Are these character vectors available online? (like word2vec or GloVe for word vectors)
Thank you.

**Comment by yoonkim** [comment]
the character model is from 
https://arxiv.org/abs/1508.06615
roughly, cnn + highway over character embeddings

**Comment by alashkari** [comment]
I meant that for each character, we have a d-dimensional vector representation; and since d<|C|, one-hot representation is not used here.
How are we assigning these vectors to characters? Are they random values?

Thank you.

**Comment by yoonkim** [comment]
They are randomly initialized and then trained along with the rest of the model.
