### ISSUE TITLE
train_from not working for old models

### ISSUE THREAD

**Issue by ankitag9** [harvardnlp/seq2seq-attn#56]
Hi,

I have a trained model which was trained using an old repo version (without attn). Now that I am trying to fine tune that model, it gives me this error - 
/home/turing/torch/install/bin/luajit: /home/turing/torch/install/share/lua/5.1/nn/MM.lua:25: second input tensor must be 2D
stack traceback:
    [C]: in function 'assert'
    /home/turing/torch/install/share/lua/5.1/nn/MM.lua:25: in function 'func'
    ...e/turing/torch/install/share/lua/5.1/nngraph/gmodule.lua:311: in function 'neteval'
    ...e/turing/torch/install/share/lua/5.1/nngraph/gmodule.lua:346: in function 'func'
    ...e/turing/torch/install/share/lua/5.1/nngraph/gmodule.lua:311: in function 'neteval'
    ...e/turing/torch/install/share/lua/5.1/nngraph/gmodule.lua:346: in function 'forward'
    train.lua:422: in function 'train_batch'
    train.lua:633: in function 'train'
    train.lua:892: in function 'main'
    train.lua:895: in main chunk
    [C]: in function 'dofile'
    ...ring/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670

Can you suggest where is the error coming from?

**Comment by yoonkim** [comment]
Hmm, I can't be sure but it seems like the model is still trying to use attention? There have been quite a few changes recently--if it's not too big of a deal I suggest retraining from scratch, sorry!

**Comment by ankitag9** [comment]
Even a model trained on the new code(with attn) cannot be preloaded. It is giving the same error.

**Comment by jsenellart-systran** [comment]
do you have the same error that the one above?

**Comment by jungikim** [comment]
Ankitag9, could you let us know the commit ID with which you have the issue?

**Comment by ankitag9** [comment]
yes i am having the same error. The commit ID is 03c365c.

**Comment by guillaumekln** [comment]
We confirm that the `-train_from` feature can be broken with old models. #60 should fix this.

However, we are unable to reproduce the error with a model trained on 03c365c. Are you sure you didn't test with a similarly old model?

**Comment by ankitag9** [comment]
I will checkout the latest version. Thanks for the fix 👍
