### ISSUE TITLE
Visualize attention weights

### ISSUE THREAD

**Issue by fbrad** [harvardnlp/seq2seq-attn#58]
Hi! I was wondering if you guys plan on adding support for easy retrieval of the attention weights during decoding? This would be really helpful for qualitative analysis.

Thanks!

**Comment by srush** [comment]
Yes, we are working on this. We will try to get it in at least a branch soon-ish.

**Comment by sebastianGehrmann** [comment]
Just pushed a file to the branch [attention_retrieval](github/harvardnlp/seq2seq-attn/tree/attention_retrieval)

**Comment by yoonkim** [comment]
thanks sebastian! closing
