### ISSUE TITLE
Data parallel training

### ISSUE THREAD

**Issue by hrishikeshvganu** [harvardnlp/seq2seq-attn#59]
I noticed that the model allows for "model parallel" training. Does the code automatically support **"data parallel"** training(without explicitly assigning data to different GPUs)?

My goal is to see if I can get approximately linear speed up using the 16 GPU machines from AWS.

**Comment by yoonkim** [comment]
Hi, the code does not support data parallelism. I haven't experimented with data parallelism in torch but from some light googling it seems like it should be possible--let us know if you end up implementing it and we'll merge!
