### ISSUE TITLE
out of memory during the training

### ISSUE THREAD

**Issue by jdxyw** [harvardnlp/seq2seq-attn#65]
Hi

I am trying to train a seq2seq model like it using my own dataset

> th train.lua -data_file ../../data/demo-train.hdf5 -val_data_file ../../data/demo-val.hdf5 -savefile model-demo -brnn 1 -attn 1 -multi_attn 3 -gpuid 3 -max_batch_l 64 -lr_decay 0.8 -num_layers 4 -rnn_size 1024 -dropout 0.3 -curriculum 1

At the beginning, it works well. However, after 4800 batch, it threw an error about out of memory.

My machine has 196G memory with Tesla K40m. Since the training has begun, why it would fail during the training.

> Epoch: 1, Batch: 4800/15072, Batch size: 64, LR: 1.0000, PPL: 246.53, |Param|: 690.31, |GParam|: 5.21, Training: 1817/1308/509 total/source/target tokens/sec
> Epoch: 1, Batch: 4850/15072, Batch size: 64, LR: 1.0000, PPL: 244.21, |Param|: 691.18, |GParam|: 5.53, Training: 1816/1311/505 total/source/target tokens/sec
> Epoch: 1, Batch: 4900/15072, Batch size: 64, LR: 1.0000, PPL: 241.79, |Param|: 692.06, |GParam|: 5.30, Training: 1815/1314/501 total/source/target tokens/sec
> Epoch: 1, Batch: 4950/15072, Batch size: 64, LR: 1.0000, PPL: 239.34, |Param|: 692.97, |GParam|: 5.76, Training: 1814/1317/496 total/source/target tokens/sec
> Epoch: 1, Batch: 5000/15072, Batch size: 64, LR: 1.0000, PPL: 236.97, |Param|: 693.87, |GParam|: 6.32, Training: 1813/1321/492 total/source/target tokens/sec
> Epoch: 1, Batch: 5050/15072, Batch size: 64, LR: 1.0000, PPL: 234.39, |Param|: 694.76, |GParam|: 5.80, Training: 1812/1324/488 total/source/target tokens/sec
> THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-2002/cutorch/lib/THC/generic/THCStorage.cu line=40 error=2 : out of memory
> /home/work/dev/torch/distro/install/bin/luajit: ...v/torch/distro/install/share/lua/5.1/nngraph/nesting.lua:34: cuda runtime error (2) : out of memory at /tmp/luarocks_cutorch-scm-1-2002/cutorch/lib/THC/generic/THCStorage.cu:40
> stack traceback:
>         [C]: in function 'resizeAs'
>         ...v/torch/distro/install/share/lua/5.1/nngraph/nesting.lua:34: in function 'resizeNestedAs'
>         ...v/torch/distro/install/share/lua/5.1/nngraph/gmodule.lua:37: in function 'getTotalGradOutput'
>         ...v/torch/distro/install/share/lua/5.1/nngraph/gmodule.lua:404: in function 'neteval'
>         ...v/torch/distro/install/share/lua/5.1/nngraph/gmodule.lua:454: in function 'updateGradInput'
>         ...v/torch/distro/install/share/lua/5.1/nngraph/gmodule.lua:420: in function 'neteval'
>         ...v/torch/distro/install/share/lua/5.1/nngraph/gmodule.lua:454: in function 'updateGradInput'
>         ...ork/dev/torch/distro/install/share/lua/5.1/nn/Module.lua:31: in function 'backward'
>         train.lua:535: in function 'train_batch'
>         train.lua:745: in function 'train'
>         train.lua:1071: in function 'main'
>         train.lua:1074: in main chunk
>         [C]: in function 'dofile'
>         ...rch/distro/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
>         [C]: at 0x00405810

**Comment by yoonkim** [comment]
GPU memory usage is a (linear-ish) function of your source sequence length. Source sequence length varies for each batch. It's likely that the max source sequence length occurred around batch 5050, hence the failure.

**Comment by jdxyw** [comment]
Hi @yoonkim

If I want to solve this problem, I have those options below,  am I right? Is there any other methods?

1. make the network structure smaller, like smaller layers, less rnn_size.
2. reduce the batch size. Currently, the batch size is 64.
3. reduce the sequence length.
4. split the training to multiple-GPU, encode for gpu-device 0 and decode for gpu-device 1

**Comment by yoonkim** [comment]
that is correct
