### ISSUE TITLE
maybe a bug

### ISSUE THREAD

**Issue by codyhan** [harvardnlp/seq2seq-attn#73]
Hi, when I read the code in line 184 to 187 from model.lua.  The code is as follows,
`  local attn = nn.MM():usePrealloc("dec_attn_mm1",
                                   {{opt.max_batch_l, opt.max_sent_l_src, opt.rnn_size},{opt.rnn_size, opt.rnn_size, 1}},
                                   {{opt.max_batch_l, opt.max_sent_l_src, 1}})
({context, nn.Replicate(1,3)(target_t)}) -- batch_l x source_l x 1`

It seems not straight forward to me. The memory you allocate for the second tensor seems not big enough. Should it be the code below?
 `  local attn = nn.MM():usePrealloc("dec_attn_mm1",
                                   {{opt.max_batch_l, opt.max_sent_l_src, opt.rnn_size},{opt.max_batch_l, opt.rnn_size, 1}},
                                   {{opt.max_batch_l, opt.max_sent_l_src, 1}})
({context, nn.Replicate(1,3)(target_t)}) -- batch_l x source_l x 1`

Or maybe I didn't understand usePrealloc correctly. Just for your information

**Comment by helson73** [comment]
[https://github.com/harvardnlp/seq2seq-attn/issues/70](url)
It may help.

**Comment by jsenellart-systran** [comment]
Thanks @codyhan and @helson73 for the feedback - it is indeed the same point than in #70. For your information, we have been refactoring all of this preallocation mechanism and we have a far cleaner and more efficient shared memory implementation that will come in few days. keep tuned!

**Comment by codyhan** [comment]
Thanks for your help~~
