### ISSUE TITLE
Tiny bug in preprocessing.py

### ISSUE THREAD

**Issue by helson73** [harvardnlp/seq2seq-attn#75]
In "preprocess.py", line 331
`l_location.append(len(sources))`
should be revised to 
`l_location.append(len(sources)+1)`
otherwise last sentence would be missing.
l_location's element always follows base index of 1 (lua), and the last element of l_location should point to len(sources), which is len(source) + 1 in lua.

**Comment by yoonkim** [comment]
thanks! this has been fixed

**Comment by helson73** [comment]
@yoonkim  BTW, in preprocess-shards.py, line 201 has the same problem :)

**Comment by yoonkim** [comment]
of course :). fixed
