### ISSUE TITLE
total_loss_cll with nil value

### ISSUE THREAD

**Issue by oraveczcsaba** [harvardnlp/seq2seq-attn#78]
When training with shards and guided alignment I get this error:

train.lua:737: attempt to perform arithmetic on local 'total_loss_cll' (a nil value)

Perhaps an initial assignment  of "total_loss_cll = 0" is missing
(which is there for total_loss and total_nonzeros).

**Comment by yoonkim** [comment]
you are right. just fixed, thanks!
