### ISSUE TITLE
What is the input of decoder?

### ISSUE THREAD

**Issue by anoidgit** [harvardnlp/seq2seq-attn#79]
I want to write a NMT, but I do not understand how to do beam search while decode. I think the input of decoder at time-step t is the output of the decoder at time-step t-1 and the output of attention at t-1, but if it works in this case, how the word selected at time-step t-1 affects sequence later.
I'm confused with this problem, and maybe I have misunderstood somewhere. Thank you if you could help me with that.

**Comment by yoonkim** [comment]
You are right, input to decoder at time step t is the output of the decoder at time-step t-1, as well as the attention vector (i.e. weighted sum of of the source hidden states) at time step t-1. The latter is optional and can be turned off by doing -input_feed 0

**Comment by anoidgit** [comment]
Thank you for your help, This have confused me for a long time. @yoonkim
