### ISSUE TITLE
when i try to train model gets below error----hdf5

### ISSUE THREAD

**Issue by akshataph** [harvardnlp/seq2seq-attn#90]
akshata@akshata-Inspiron-3551:~/torch/seq2seq-attn-master$ th train.lua -data_file data/demo-train.hdf5 -val_data_file data/demo-val.hdf5 -savefile demo-model
/home/akshata/torch/install/bin/lua: /home/akshata/torch/install/share/lua/5.2/trepl/init.lua:389: module 'hdf5' not found:No LuaRocks module found for hdf5
	no field package.preload['hdf5']
	no file '/home/akshata/.luarocks/share/lua/5.2/hdf5.lua'
	no file '/home/akshata/.luarocks/share/lua/5.2/hdf5/init.lua'
	no file '/home/akshata/torch/install/share/lua/5.2/hdf5.lua'
	no file '/home/akshata/torch/install/share/lua/5.2/hdf5/init.lua'
	no file '/home/akshata/.luarocks/share/lua/5.1/hdf5.lua'
	no file '/home/akshata/.luarocks/share/lua/5.1/hdf5/init.lua'
	no file '/home/akshata/torch/install/share/lua/5.1/hdf5.lua'
	no file '/home/akshata/torch/install/share/lua/5.1/hdf5/init.lua'
	no file './hdf5.lua'
	no file '/home/akshata/torch/install/share/luajit-2.1.0-beta1/hdf5.lua'
	no file '/usr/local/share/lua/5.1/hdf5.lua'
	no file '/usr/local/share/lua/5.1/hdf5/init.lua'
	no file '/home/akshata/.luarocks/lib/lua/5.2/hdf5.so'
	no file '/home/akshata/torch/install/lib/lua/5.2/hdf5.so'
	no file '/home/akshata/torch/install/lib/hdf5.so'
	no file '/home/akshata/.luarocks/lib/lua/5.1/hdf5.so'
	no file '/home/akshata/torch/install/lib/lua/5.1/hdf5.so'
	no file './hdf5.so'
	no file '/usr/local/lib/lua/5.1/hdf5.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/home/akshata/torch/install/share/lua/5.2/trepl/init.lua:389: in function 'require'
	train.lua:3: in main chunk
	[C]: in function 'dofile'
	...hata/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: in ?

**Comment by chudonezen** [comment]
I have the same question , have you figured out it?

**Comment by guillaumekln** [comment]
You just need to install the `hdf5` package:

```
luarocks install hdf5
```

**Comment by chudonezen** [comment]
thank you，i have figured out it with your reply☺️

**Comment by Angus1996** [comment]
> You just need to install the `hdf5` package:
> 
> ```
> luarocks install hdf5
> ```

I met a new problem when I was doing this. It shows that "Missing dependencies for hdf5:
logroll "
