### ISSUE TITLE
how to use s2sa/scorers/bleu.lua

### ISSUE THREAD

**Issue by IdiosyncraticDragon** [harvardnlp/seq2seq-attn#93]
I found it was not very convenient to use multi-bleu.perl to calculate BLEU score every time, especially when I wanted to get the BLEU score inside a lua program. I find there is a file called bleu.lua under s2sa/scorers/ which seems like a program to compute BLEU scores. Is there any usage for the bleu.lua?

**Comment by yoonkim** [comment]
Yes, get_ngram_prec basically calculates the ngram precisions, which you can use to get corpus level (or sentence level) bleu. See evaluate.lua with the scorer option to see how this is calc'ed at sentence level.
