### ISSUE TITLE
How to compute the probability for a pair of input and output sentences?

### ISSUE THREAD

**Issue by ayushidalmia** [harvardnlp/seq2seq-attn#96]
Hi,

I am interested in computing the probabilities for a given pair of input and output sentences. Is there a provision to do the same? Where should I look into.

Thanks

**Comment by yoonkim** [comment]
You can use the score from beam search.
The score is essentially log p(target | source)

**Comment by ayushidalmia** [comment]
Yeah! Got it. Thanks!
