### ISSUE TITLE
Sequence-to-Sequence Learning as Beam-Search Optimization

### ISSUE THREAD

**Issue by jndevanshu** [harvardnlp/seq2seq-attn#99]
Hi,

I was reading the paper titled 'Sequence-to-Sequence Learning as Beam-Search Optimization' by Sam Wiseman and Alexander M. Rush. Can someone please tell me where can I find the implementation of the same? Is it implemented in this repository? I could not find any documentation for that here.

Thanks 
Devanshu

**Comment by swiseman** [comment]
https://github.com/harvardnlp/BSO

**Comment by jndevanshu** [comment]
Thanks
